-- ============================================================
-- Mở rộng System Vocabulary: thêm ~150 từ mới (A1-C2)
-- Tổng sau migration: ~215 từ (đủ dùng ~20 ngày)
-- ============================================================

INSERT INTO system_vocabulary (word, pos, phonetic, definition, translation, example_sentence, level, topic)
VALUES
-- ==================== A1 - Thêm 20 từ ====================
('water', 'noun', '/ˈwɔːtə/', 'A clear liquid that has no color, taste, or smell.', 'Nước', 'I drink a lot of water every day.', 'A1', 'Food'),
('friend', 'noun', '/frend/', 'A person you know well and like.', 'Bạn bè', 'She is my best friend from school.', 'A1', 'People'),
('help', 'verb', '/help/', 'Make it easier for someone to do something.', 'Giúp đỡ', 'Can you help me carry this bag?', 'A1', 'Verbs'),
('happy', 'adj', '/ˈhæpi/', 'Feeling or showing pleasure.', 'Vui vẻ, hạnh phúc', 'I feel happy when I play with my dog.', 'A1', 'Emotions'),
('big', 'adj', '/bɪɡ/', 'Of considerable size or extent.', 'To, lớn', 'They live in a big house near the park.', 'A1', 'Adjectives'),
('work', 'verb', '/wɜːk/', 'Activity involving mental or physical effort done to achieve a purpose.', 'Làm việc', 'I work from Monday to Friday.', 'A1', 'Work'),
('like', 'verb', '/laɪk/', 'Find agreeable, enjoyable, or satisfactory.', 'Thích', 'I like chocolate ice cream.', 'A1', 'Emotions'),
('small', 'adj', '/smɔːl/', 'Of a size that is less than normal or usual.', 'Nhỏ', 'She lives in a small apartment downtown.', 'A1', 'Adjectives'),
('city', 'noun', '/ˈsɪti/', 'A large town.', 'Thành phố', 'Tokyo is a very busy city.', 'A1', 'Places'),
('food', 'noun', '/fuːd/', 'Any nutritious substance that people eat or drink.', 'Thức ăn, đồ ăn', 'Vietnamese food is delicious.', 'A1', 'Food'),
('play', 'verb', '/pleɪ/', 'Engage in activity for enjoyment rather than a serious purpose.', 'Chơi', 'The children play in the garden every afternoon.', 'A1', 'Hobbies'),
('buy', 'verb', '/baɪ/', 'Obtain in exchange for payment.', 'Mua', 'I want to buy a new phone.', 'A1', 'Actions'),
('today', 'noun', '/təˈdeɪ/', 'This present day.', 'Hôm nay', 'Today is a beautiful day.', 'A1', 'Time'),
('morning', 'noun', '/ˈmɔːnɪŋ/', 'The period of time between midnight and noon.', 'Buổi sáng', 'I wake up early every morning.', 'A1', 'Time'),
('night', 'noun', '/naɪt/', 'The period of darkness between sunset and sunrise.', 'Đêm, buổi tối', 'Good night! Sleep well.', 'A1', 'Time'),
('open', 'verb', '/ˈəʊpən/', 'Move or adjust so as to leave a space allowing access.', 'Mở', 'Please open the window.', 'A1', 'Verbs'),
('close', 'verb', '/kləʊz/', 'Move so as to cover an opening.', 'Đóng', 'Close the door, please.', 'A1', 'Verbs'),
('listen', 'verb', '/ˈlɪsn/', 'Give one''s attention to a sound.', 'Nghe', 'I like to listen to music while studying.', 'A1', 'Actions'),
('write', 'verb', '/raɪt/', 'Mark (letters, words, or other symbols) on a surface.', 'Viết', 'Please write your name on the paper.', 'A1', 'Actions'),
('speak', 'verb', '/spiːk/', 'Say something in order to convey information or to express a feeling.', 'Nói', 'She can speak three languages fluently.', 'A1', 'Communication'),

-- ==================== A2 - Thêm 20 từ ====================
('adventure', 'noun', '/ədˈventʃə/', 'An unusual and exciting or daring experience.', 'Cuộc phiêu lưu', 'Travelling alone is a great adventure.', 'A2', 'Concepts'),
('comfortable', 'adj', '/ˈkʌmftəbl/', 'Providing physical ease and relaxation.', 'Thoải mái', 'This sofa is very comfortable.', 'A2', 'Adjectives'),
('discover', 'verb', '/dɪˈskʌvə/', 'Find something unexpected or previously unknown.', 'Khám phá', 'Scientists discovered a new species of butterfly.', 'A2', 'Verbs'),
('environment', 'noun', '/ɪnˈvaɪrənmənt/', 'The surroundings in which a person, animal, or plant lives.', 'Môi trường', 'We must protect the environment.', 'A2', 'Nature'),
('familiar', 'adj', '/fəˈmɪliə/', 'Well known from long or close association.', 'Quen thuộc', 'This place looks familiar to me.', 'A2', 'Adjectives'),
('generous', 'adj', '/ˈdʒenərəs/', 'Showing a readiness to give more of something than is expected.', 'Hào phóng', 'He is very generous with his time.', 'A2', 'Adjectives'),
('honest', 'adj', '/ˈɒnɪst/', 'Free of deceit; truthful and sincere.', 'Trung thực', 'She is an honest and hardworking person.', 'A2', 'Adjectives'),
('include', 'verb', '/ɪnˈkluːd/', 'Comprise or contain as part of a whole.', 'Bao gồm', 'The price includes breakfast and lunch.', 'A2', 'Verbs'),
('prefer', 'verb', '/prɪˈfɜː/', 'Like (one thing or person) better than another.', 'Thích hơn', 'I prefer tea to coffee.', 'A2', 'Verbs'),
('quality', 'noun', '/ˈkwɒləti/', 'The standard of something as measured against other things.', 'Chất lượng', 'The quality of this product is excellent.', 'A2', 'Concepts'),
('recommend', 'verb', '/ˌrekəˈmend/', 'Put forward (someone or something) with approval as being suitable.', 'Đề xuất, giới thiệu', 'Can you recommend a good restaurant?', 'A2', 'Communication'),
('succeed', 'verb', '/səkˈsiːd/', 'Achieve the desired aim or result.', 'Thành công', 'If you work hard, you will succeed.', 'A2', 'Verbs'),
('tradition', 'noun', '/trəˈdɪʃn/', 'A long-established custom or belief.', 'Truyền thống', 'It is a tradition to eat moon cakes during Mid-Autumn Festival.', 'A2', 'Culture'),
('understand', 'verb', '/ˌʌndəˈstænd/', 'Perceive the intended meaning of (words, a speaker, or a language).', 'Hiểu', 'I understand the instructions clearly.', 'A2', 'Communication'),
('valuable', 'adj', '/ˈvæljuəbl/', 'Worth a great deal of money or extremely useful.', 'Có giá trị', 'Time is the most valuable thing we have.', 'A2', 'Adjectives'),
('weather', 'noun', '/ˈweðə/', 'The state of the atmosphere at a place and time.', 'Thời tiết', 'The weather is really nice today.', 'A2', 'Nature'),
('compare', 'verb', '/kəmˈpeə/', 'Estimate, measure, or note the similarity or dissimilarity between.', 'So sánh', 'Let''s compare the prices before buying.', 'A2', 'Actions'),
('perhaps', 'adv', '/pəˈhæps/', 'Used to express uncertainty or possibility.', 'Có lẽ', 'Perhaps we should try a different approach.', 'A2', 'Adverbs'),
('remain', 'verb', '/rɪˈmeɪn/', 'Continue to exist, especially after other similar things have ceased.', 'Còn lại', 'Only two tickets remain for tonight''s show.', 'A2', 'Verbs'),
('suggest', 'verb', '/səˈdʒest/', 'Put forward for consideration.', 'Gợi ý, đề nghị', 'I suggest we take a break and continue later.', 'A2', 'Communication'),

-- ==================== B1 - Thêm 20 từ ====================
('accomplish', 'verb', '/əˈkʌmplɪʃ/', 'Achieve or complete successfully.', 'Hoàn thành', 'She accomplished her dream of becoming a pilot.', 'B1', 'Verbs'),
('circumstance', 'noun', '/ˈsɜːkəmstəns/', 'A fact or condition connected with an event or action.', 'Hoàn cảnh', 'Under no circumstances should you leave the building.', 'B1', 'Concepts'),
('contribute', 'verb', '/kənˈtrɪbjuːt/', 'Give (something) in order to help achieve or provide something.', 'Đóng góp', 'Everyone should contribute to protecting the environment.', 'B1', 'Verbs'),
('demonstrate', 'verb', '/ˈdemənstreɪt/', 'Clearly show the existence or truth of something.', 'Chứng minh, trình diễn', 'The experiment demonstrates how gravity works.', 'B1', 'Verbs'),
('enormous', 'adj', '/ɪˈnɔːməs/', 'Very large in size, quantity, or extent.', 'Khổng lồ', 'The museum has an enormous collection of art.', 'B1', 'Adjectives'),
('fundamental', 'adj', '/ˌfʌndəˈmentl/', 'Forming a necessary base or core; of central importance.', 'Cơ bản, nền tảng', 'Education is a fundamental right for all children.', 'B1', 'Adjectives'),
('gradually', 'adv', '/ˈɡrædʒuəli/', 'In a gradual way; slowly; by degrees.', 'Dần dần', 'The temperature gradually increased throughout the day.', 'B1', 'Adverbs'),
('independent', 'adj', '/ˌɪndɪˈpendənt/', 'Free from outside control; not subject to another''s authority.', 'Độc lập', 'She became financially independent at age 25.', 'B1', 'Adjectives'),
('meanwhile', 'adv', '/ˈmiːnwaɪl/', 'In the intervening period of time.', 'Trong khi đó', 'I''ll prepare lunch; meanwhile, you can set the table.', 'B1', 'Adverbs'),
('particular', 'adj', '/pəˈtɪkjʊlə/', 'Used to single out an individual member of a specified group.', 'Cụ thể, đặc biệt', 'Is there a particular reason you chose this restaurant?', 'B1', 'Adjectives'),
('consequences', 'noun', '/ˈkɒnsɪkwənsɪz/', 'A result or effect, typically one that is unwelcome.', 'Hậu quả', 'He didn''t think about the consequences of his actions.', 'B1', 'Concepts'),
('significant', 'adj', '/sɪɡˈnɪfɪkənt/', 'Sufficiently great or important to be worthy of attention.', 'Đáng kể, quan trọng', 'There has been a significant improvement in her grades.', 'B1', 'Adjectives'),
('ultimately', 'adv', '/ˈʌltɪmətli/', 'Finally; in the end.', 'Cuối cùng', 'Ultimately, the decision is yours to make.', 'B1', 'Adverbs'),
('curiosity', 'noun', '/ˌkjʊəriˈɒsəti/', 'A strong desire to know or learn something.', 'Sự tò mò', 'Curiosity is the key to lifelong learning.', 'B1', 'Concepts'),
('obstacle', 'noun', '/ˈɒbstəkl/', 'A thing that blocks one''s way or prevents progress.', 'Trở ngại', 'Language is no longer an obstacle to communication.', 'B1', 'Concepts'),
('perspective', 'noun', '/pəˈspektɪv/', 'A particular attitude toward something; a point of view.', 'Quan điểm, góc nhìn', 'Try to see the problem from a different perspective.', 'B1', 'Concepts'),
('reliable', 'adj', '/rɪˈlaɪəbl/', 'Consistently good in quality or performance; able to be trusted.', 'Đáng tin cậy', 'She is a very reliable employee who never misses a deadline.', 'B1', 'Adjectives'),
('temporary', 'adj', '/ˈtemprəri/', 'Lasting for only a limited period of time; not permanent.', 'Tạm thời', 'This is a temporary solution until we find a better one.', 'B1', 'Adjectives'),
('volunteer', 'noun', '/ˌvɒlənˈtɪə/', 'A person who freely offers to take part in an enterprise.', 'Tình nguyện viên', 'She works as a volunteer at the local hospital.', 'B1', 'People'),
('approximately', 'adv', '/əˈprɒksɪmətli/', 'Close to the actual, but not completely accurate.', 'Xấp xỉ, khoảng', 'The journey takes approximately three hours.', 'B1', 'Adverbs'),

-- ==================== B2 - Thêm 20 từ ====================
('accumulate', 'verb', '/əˈkjuːmjəleɪt/', 'Gather together or acquire an increasing number or quantity.', 'Tích lũy', 'He accumulated a fortune through wise investments.', 'B2', 'Verbs'),
('controversy', 'noun', '/ˈkɒntrəvɜːsi/', 'Prolonged public disagreement or heated discussion.', 'Tranh cãi', 'The new policy caused a lot of controversy.', 'B2', 'Society'),
('distinguish', 'verb', '/dɪˈstɪŋɡwɪʃ/', 'Recognize or treat as different.', 'Phân biệt', 'It is important to distinguish fact from opinion.', 'B2', 'Verbs'),
('elaborate', 'adj', '/ɪˈlæbərət/', 'Involving many carefully arranged parts or details.', 'Tinh xảo, công phu', 'She wore an elaborate costume to the festival.', 'B2', 'Adjectives'),
('fluctuate', 'verb', '/ˈflʌktʃueɪt/', 'Rise and fall irregularly in number or amount.', 'Dao động', 'Oil prices fluctuate depending on global demand.', 'B2', 'Business'),
('hypothesis', 'noun', '/haɪˈpɒθəsɪs/', 'A supposition made as a starting point for investigation.', 'Giả thuyết', 'Scientists tested the hypothesis with a new experiment.', 'B2', 'Science'),
('implication', 'noun', '/ˌɪmplɪˈkeɪʃn/', 'The conclusion that can be drawn from something.', 'Hàm ý, tác động', 'The policy has serious implications for public health.', 'B2', 'Concepts'),
('legitimate', 'adj', '/lɪˈdʒɪtɪmət/', 'Conforming to the law or to rules.', 'Hợp pháp, chính đáng', 'She had a legitimate reason for being absent.', 'B2', 'Society'),
('misconception', 'noun', '/ˌmɪskənˈsepʃn/', 'A view or opinion that is incorrect because based on faulty thinking.', 'Quan niệm sai lầm', 'There is a common misconception that sugar causes hyperactivity.', 'B2', 'Concepts'),
('phenomenon', 'noun', '/fɪˈnɒmɪnən/', 'A fact or situation that is observed to exist or happen.', 'Hiện tượng', 'The Northern Lights are a remarkable natural phenomenon.', 'B2', 'Science'),
('contradiction', 'noun', '/ˌkɒntrəˈdɪkʃn/', 'A combination of statements or ideas that are opposed to one another.', 'Mâu thuẫn', 'There was a contradiction between his words and actions.', 'B2', 'Concepts'),
('simultaneously', 'adv', '/ˌsɪmlˈteɪniəsli/', 'At the same time.', 'Đồng thời', 'She can manage multiple projects simultaneously.', 'B2', 'Adverbs'),
('sophisticated', 'adj', '/səˈfɪstɪkeɪtɪd/', 'Having a great deal of worldly experience and knowledge.', 'Tinh vi, phức tạp', 'The latest smartphones have very sophisticated cameras.', 'B2', 'Adjectives'),
('sustainability', 'noun', '/səˌsteɪnəˈbɪləti/', 'The ability to be maintained at a certain rate or level.', 'Tính bền vững', 'Environmental sustainability is crucial for future generations.', 'B2', 'Nature'),
('undergo', 'verb', '/ˌʌndəˈɡəʊ/', 'Experience or be subjected to (something, typically unpleasant).', 'Trải qua', 'The building is undergoing major renovations.', 'B2', 'Verbs'),
('vulnerability', 'noun', '/ˌvʌlnərəˈbɪləti/', 'The quality of being exposed to the possibility of harm.', 'Tính dễ tổn thương', 'Sharing your vulnerability takes great courage.', 'B2', 'Concepts'),
('bureaucracy', 'noun', '/bjʊˈrɒkrəsi/', 'A system of government with many complicated rules and processes.', 'Bộ máy quan liêu', 'Too much bureaucracy can slow down business growth.', 'B2', 'Society'),
('deteriorate', 'verb', '/dɪˈtɪəriəreɪt/', 'Become progressively worse.', 'Xuống cấp, suy giảm', 'The patient''s condition continued to deteriorate overnight.', 'B2', 'Verbs'),
('paradigm', 'noun', '/ˈpærədaɪm/', 'A typical example or pattern of something.', 'Mô hình, khuôn mẫu', 'The internet has created a new paradigm in communication.', 'B2', 'Concepts'),
('unprecedented', 'adj', '/ʌnˈpresɪdentɪd/', 'Never done or known before.', 'Chưa từng có', 'The pandemic caused unprecedented changes in daily life.', 'B2', 'Adjectives'),

-- ==================== C1 - Thêm 20 từ ====================
('acquiesce', 'verb', '/ˌækwiˈes/', 'Accept something reluctantly but without protest.', 'Miễn cưỡng đồng ý', 'She acquiesced to her parents'' decision to move abroad.', 'C1', 'Verbs'),
('belligerent', 'adj', '/bəˈlɪdʒərənt/', 'Hostile and aggressive.', 'Hiếu chiến, hung hăng', 'The manager''s belligerent attitude upset the entire team.', 'C1', 'Adjectives'),
('circumvent', 'verb', '/ˌsɜːkəmˈvent/', 'Find a way around (an obstacle).', 'Né tránh, lách luật', 'Companies try to circumvent tax regulations.', 'C1', 'Verbs'),
('dichotomy', 'noun', '/daɪˈkɒtəmi/', 'A division or contrast between two things.', 'Sự phân đôi, chia rẽ', 'There is a dichotomy between his public and private persona.', 'C1', 'Concepts'),
('eloquent', 'adj', '/ˈeləkwənt/', 'Fluent or persuasive in speaking or writing.', 'Hùng biện, ăn nói hay', 'She gave an eloquent speech at the conference.', 'C1', 'Communication'),
('fallacy', 'noun', '/ˈfæləsi/', 'A mistaken belief, especially one based on unsound arguments.', 'Sự ngụy biện', 'It is a fallacy that money always brings happiness.', 'C1', 'Concepts'),
('gregarious', 'adj', '/ɡrɪˈɡeəriəs/', 'Fond of company; sociable.', 'Hòa đồng, thích giao du', 'He is a gregarious person who loves meeting new people.', 'C1', 'People'),
('idiosyncratic', 'adj', '/ˌɪdiəsɪŋˈkrætɪk/', 'Relating to the nature of a particular person; peculiar.', 'Có tính riêng biệt, kỳ quặc', 'Each language has its own idiosyncratic grammar rules.', 'C1', 'Adjectives'),
('juxtapose', 'verb', '/ˈdʒʌkstəpəʊz/', 'Place side by side for comparison or contrast.', 'Đặt cạnh nhau để so sánh', 'The exhibit juxtaposes modern art with classical paintings.', 'C1', 'Verbs'),
('meticulous', 'adj', '/məˈtɪkjʊləs/', 'Showing great attention to detail; very careful and precise.', 'Tỉ mỉ, kỹ lưỡng', 'She is meticulous about keeping her workspace organized.', 'C1', 'Adjectives'),
('nonchalant', 'adj', '/ˈnɒnʃələnt/', 'Feeling or appearing casually calm and relaxed.', 'Thờ ơ, bình thản', 'He tried to appear nonchalant despite his nervousness.', 'C1', 'Adjectives'),
('paradox', 'noun', '/ˈpærədɒks/', 'A seemingly absurd or contradictory statement that may be true.', 'Nghịch lý', 'It is a paradox that the richest people are often the unhappiest.', 'C1', 'Concepts'),
('quintessential', 'adj', '/ˌkwɪntɪˈsenʃl/', 'Representing the most perfect example of a quality or class.', 'Tinh túy, điển hình nhất', 'Phở is the quintessential Vietnamese dish.', 'C1', 'Adjectives'),
('surreptitious', 'adj', '/ˌsʌrəpˈtɪʃəs/', 'Kept secret, especially because it would not be approved of.', 'Lén lút', 'She took a surreptitious glance at her phone during the meeting.', 'C1', 'Adjectives'),
('tenacious', 'adj', '/tɪˈneɪʃəs/', 'Tending to keep a firm hold of something; determined.', 'Kiên trì, bền bỉ', 'She is a tenacious researcher who never gives up.', 'C1', 'Adjectives'),
('vicarious', 'adj', '/vɪˈkeəriəs/', 'Experienced in the imagination through another person.', 'Gián tiếp qua trải nghiệm của người khác', 'She lives vicariously through her daughter''s adventures.', 'C1', 'Concepts'),
('ambivalent', 'adj', '/æmˈbɪvələnt/', 'Having mixed feelings or contradictory ideas about something.', 'Nửa vời, phân vân', 'He felt ambivalent about leaving his hometown.', 'C1', 'Emotions'),
('conundrum', 'noun', '/kəˈnʌndrəm/', 'A confusing and difficult problem or question.', 'Câu hỏi hóc búa', 'Climate change poses a global conundrum for policymakers.', 'C1', 'Concepts'),
('exacerbate', 'verb', '/ɪɡˈzæsəbeɪt/', 'Make (a problem or bad situation) worse.', 'Làm trầm trọng thêm', 'Lack of sleep can exacerbate health problems.', 'C1', 'Verbs'),
('pragmatic', 'adj', '/præɡˈmætɪk/', 'Dealing with things sensibly and realistically.', 'Thực dụng', 'We need a pragmatic approach to solve this issue.', 'C1', 'Adjectives'),

-- ==================== C2 - Thêm 15 từ ====================
('abnegate', 'verb', '/ˈæbnɪɡeɪt/', 'Renounce or reject (something desired or valuable).', 'Từ bỏ', 'She abnegated all personal comforts to serve the community.', 'C2', 'Verbs'),
('capricious', 'adj', '/kəˈprɪʃəs/', 'Given to sudden and unaccountable changes of mood or behavior.', 'Thất thường, hay thay đổi', 'The capricious weather made it impossible to plan outdoor events.', 'C2', 'Adjectives'),
('dilapidated', 'adj', '/dɪˈlæpɪdeɪtɪd/', 'In a state of disrepair or ruin as a result of age or neglect.', 'Đổ nát, xuống cấp', 'The dilapidated building was scheduled for demolition.', 'C2', 'Adjectives'),
('evanescent', 'adj', '/ˌevəˈnesnt/', 'Soon passing out of sight, memory, or existence.', 'Phù du, mau tàn', 'Youth is evanescent, so cherish every moment.', 'C2', 'Concepts'),
('fastidious', 'adj', '/fæˈstɪdiəs/', 'Very attentive to and concerned about accuracy and detail.', 'Kỹ tính, cầu kỳ', 'He is fastidious about grammar and word choice.', 'C2', 'Adjectives'),
('magnanimous', 'adj', '/mæɡˈnænɪməs/', 'Generous or forgiving, especially toward a rival.', 'Độ lượng, rộng lượng', 'The victor was magnanimous in his treatment of the defeated.', 'C2', 'Adjectives'),
('ostentatious', 'adj', '/ˌɒstenˈteɪʃəs/', 'Designed to impress or attract notice.', 'Phô trương, khoa trương', 'The billionaire''s ostentatious lifestyle shocked many people.', 'C2', 'Adjectives'),
('perfunctory', 'adj', '/pəˈfʌŋktəri/', 'Carried out without real interest, feeling, or effort.', 'Chiếu lệ, qua loa', 'He gave a perfunctory nod and went back to his work.', 'C2', 'Adjectives'),
('recalcitrant', 'adj', '/rɪˈkælsɪtrənt/', 'Having an obstinately uncooperative attitude.', 'Bướng bỉnh, chống đối', 'The recalcitrant student refused to follow the rules.', 'C2', 'Adjectives'),
('sycophant', 'noun', '/ˈsɪkəfænt/', 'A person who acts obsequiously toward someone important.', 'Kẻ nịnh bợ', 'The manager was surrounded by sycophants who agreed with everything.', 'C2', 'People'),
('trepidation', 'noun', '/ˌtrepɪˈdeɪʃn/', 'A feeling of fear or anxiety about something that may happen.', 'Sự lo sợ, e ngại', 'She felt a sense of trepidation before her job interview.', 'C2', 'Emotions'),
('verisimilitude', 'noun', '/ˌverɪsɪˈmɪlɪtjuːd/', 'The appearance of being true or real.', 'Tính chân thực', 'The movie''s verisimilitude made viewers forget it was fiction.', 'C2', 'Concepts'),
('zeitgeist', 'noun', '/ˈzaɪtɡaɪst/', 'The spirit or mood of a particular period of history.', 'Tinh thần thời đại', 'Social media captures the zeitgeist of modern society.', 'C2', 'Society'),
('serendipity', 'noun', '/ˌserənˈdɪpəti/', 'The occurrence of events by chance in a happy way.', 'Duyên may, tình cờ may mắn', 'Meeting my best friend on that trip was pure serendipity.', 'C2', 'Concepts'),
('inscrutable', 'adj', '/ɪnˈskruːtəbl/', 'Impossible to understand or interpret.', 'Khó hiểu, bí ẩn', 'Her inscrutable expression gave nothing away.', 'C2', 'Adjectives')

ON CONFLICT (word) DO UPDATE SET
    definition = EXCLUDED.definition,
    translation = EXCLUDED.translation,
    example_sentence = EXCLUDED.example_sentence,
    phonetic = EXCLUDED.phonetic,
    pos = EXCLUDED.pos,
    level = EXCLUDED.level,
    topic = EXCLUDED.topic,
    updated_at = NOW();
