-- =============================================================================
-- Learning Hub Feature - Database Migration
-- Created: 2026-02-26
-- Description: Tracking micro-learning lessons generated by AI
-- =============================================================================

CREATE TABLE IF NOT EXISTS learning_history (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL CHECK (category IN ('grammar', 'pattern', 'pronunciation')),
    level VARCHAR(2) NOT NULL CHECK (level IN ('A1','A2','B1','B2','C1','C2')),
    title VARCHAR(255) NOT NULL,
    score INT DEFAULT 0, -- Score from follow-up quiz
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lh_user ON learning_history(user_id);
CREATE INDEX IF NOT EXISTS idx_lh_user_category ON learning_history(user_id, category);

-- End of Learning Hub Migration
